version: "3.8"

services:
    article-bdd:
        build: ./articles-db
        image: articles-bdd
        container_name: articles-bdd
        networks: 
            - articles-network
        volumes:
            - articles-bdd-data:/var/lib/mysql


    articles-back:
        build: ./articles-back
        image: articles-back
        container_name: articles-back
        ports:
            - "8081:8080"
        depends_on:
            - article-bdd
        networks:
            - articles-network

    articles-front:
        build: ./articles-front
        image: articles-front
        container_name: articles-front
        ports:
            - "9000:80"
        depends_on:
            - articles-back
        networks: 
            - articles-network
        
networks:
    articles-network:

volumes:
    articles-bdd-data: